package net.courses.model;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Course model - represents a single course in the CodeCraftHub platform.
 *
 * Jackson's @JsonProperty maps Java camelCase fields to JSON snake_case keys,
 * so the JSON file and API requests/responses use "target_date" and "created_at"
 * while the Java code uses "targetDate" and "createdAt".
 */
public class Course {

    // Unique identifier, auto-generated by the service
    private Long id;

    // Course title - required
    private String name;

    // What the course covers - required
    private String description;

    // Expected completion date in YYYY-MM-DD format - required
    @JsonProperty("target_date")
    private String targetDate;

    // Learning progress: "Not Started", "In Progress", or "Completed" - required
    private String status;

    // Timestamp set automatically when the course is first created
    @JsonProperty("created_at")
    private String createdAt;

    // Jackson requires a no-arg constructor to deserialize JSON into this object
    public Course() {}

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getTargetDate() { return targetDate; }
    public void setTargetDate(String targetDate) { this.targetDate = targetDate; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public String getCreatedAt() { return createdAt; }
    public void setCreatedAt(String createdAt) { this.createdAt = createdAt; }
}
